[book]
title = "Rust via Desugarings"
description = "A book that explains the meaning of a Rust program via successive desugarings"
authors = ["Nadrieril"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/Nadrieril/rust-via-desugarings"
edit-url-template = "https://github.com/Nadrieril/rust-via-desugarings/edit/main/{path}"
site-url = "/rust-via-desugarings/"

[output.html.fold]
enable = true
level = 1

[output.linkcheck]
optional = true
warning-policy = "error"
