[workspace]
resolver = "3"
members = ["cargo-desugar"]

[package]
name = "rust-via-desugarings"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_via_desugarings"
path = "src/lib.rs"

[dependencies]
itertools = "0.14.0"
prettyplease = "0.2"
syn = { version = "2", features = ["parsing"] }

[package.metadata.rust-analyzer]
rustc_private = true
